### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kevbook** [ericelliott/react-pure-component-starter#175]
Question about pure components: I am passing props from parent to pure component, can I do something like "shouldComponentUpdate" because I don't want it to re-render. Or do I have to do that somehow in the parent component?

**Comment by ericelliott** [comment]
Do you use Redux? If so, the `connect()` utility from [react-redux](https://github.com/reactjs/react-redux) implements [`shouldComponentUpdate`](https://github.com/reactjs/react-redux/blob/93cdfaeaf9d3e5400ffc05fe9d177118286109ca/src/components/connect.js#L60) for you automatically. One of the many benefits of using Redux.

=)

I usually have a smart component that knows about the store -- that's the one that gets the `connect()` love. Child components are all dumb -- they know nothing about state, and none of them implement lifecycle methods unless they need to animate or interact with the DOM.

**Comment by kevbook** [comment]
Thanks, my question was less around implementation but more about internals of pure components. Can pure components have `shouldComponentUpdate` type of lifecycle hook. In a class component, I suppose `shouldComponentUpdate` runs first, and render or other methods will not even run, if it returns **false**.

I may have answered my own question, a pure component is just a function so i cant have previous props (or state) to implement a **shouldComponentUpdate** function, so the parent must do that. And like you said, redux does that for you with `connect()`

Please correct me here, if I am wrong. Thanks

**Comment by ericelliott** [comment]
You got it. :+1: =)

A pure component is just a function. It doesn't need lifecycle methods. If you do need lifecycle methods for your component, you should consider using an alternative API, such as [react-stamp](https://github.com/stampit-org/react-stamp) or (if you must) the `class` syntax.

If you decide to use the `class` syntax, read this first: ["How to Use Classes and Sleep at Night"](https://medium.com/@dan_abramov/how-to-use-classes-and-sleep-at-night-9af8de78ccb4).
