### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by pablopaul** [ericelliott/react-pure-component-starter#216]
What is the actual implementation state of the "hot reloading" feature in this repo? A fresh install of the repo shows the following console output after a file change:

```
[HMR] connected
client.js:123 [HMR] bundle rebuilding
client.js:126 [HMR] bundle rebuilt in 450ms
process-update.js:27 [HMR] Checking for updates on the server...
process-update.js:81 [HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.
process-update.js:89 [HMR]  - ./source/index.js
```

**Comment by ericelliott** [comment]
HMR doesn't work with pure components. );

We should remove the feature. Want to PR?

**Comment by pablopaul** [comment]
Can you give some context why HMR is not working with pure components? 

Yes I will make a PR.

**Comment by ericelliott** [comment]
It's a known issue with HMR in general. [Discussion is here](https://github.com/gaearon/babel-plugin-react-transform/issues/57).

**Comment by gaearon** [comment]
React Hot Loader 3 supports functional components without destroying the state.
It supersedes both React Hot Loader and React Transform, and is built on lessons learned from both.
Check it out: https://github.com/gaearon/react-hot-boilerplate/pull/61

**Comment by pablopaul** [comment]
@ericelliott I suggest we are waiting for React Hot Loader 3, right?

**Comment by gaearon** [comment]
Note it might take quite a while to release as stable because I have no time to work on docs or website right now. Those are the blockers. See https://github.com/gaearon/react-hot-loader/issues/243.
