### ISSUE TITLE
devServer.js config with environment variable

### ISSUE THREAD

**Issue by pdavidow** [ericelliott/react-pure-component-starter#228]
In devServer.js, instead of

```
app.listen(3000, 'localhost', function (err) {
```

for Cloud9 this should be:

```
app.listen(8080, '0.0.0.0', function(err) { 
```

and Nitrous.io:

```
app.listen(3000, '0.0.0.0', function (err) {
```

This could be configured with an environment variable.

The console.log output of course would also need to be updated, and for Cloud9 should also mention that _Open in Preview_ should not be used.

**Comment by ericelliott** [comment]
Would you like to file a pull request? =)

I don't think we need to specifically mention Cloud9. The environment variables should be enough to allow users to make it work on Cloud9.

**Comment by pdavidow** [comment]
Perhaps another approach is a flag on _npm start_.
Environment Variables are only for Windows (I think), but what if someone wants to run Cloud9 say from a Chromebook? Plus, even on Windows, someone may have an account both on Cloud9 **and** Nitrous etc.

**Comment by ericelliott** [comment]
Environment variables work great on any platform, but the way you set them varies depending on platform. However, we should not care about how it gets set, and only respect the environment variables if they are set.

So, for example, you could create `host` and `port` variables like this:

``` js
const {
  host = 'localhost',
  port = 3000
} = process.env;
```

Now in your cloud9 console, you can set the environment variable before launching the service:

```
set HOST='0.0.0.0'
set PORT=8080
npm start
```

**Comment by pdavidow** [comment]
I see, and the Readme would give the details for Cloud9, Nitrous etc.
But what is wrong with having:
````
set cloud='c9'
npm start
````
Is it that if Cloud9 would ever change their config, the burden is on the software maintainer -- and not the user -- to conform to the update? But even so, the Readme (part of the 'software') would still need to be updated. One might suggest that the Readme simply end with caveat 'as of this writing' after giving the hardcoded constants...

**Comment by pdavidow** [comment]
I plan to file pull request for this.

**Comment by pdavidow** [comment]
There doesn't seem to be anything to test, so don't know how to write test for this.

Also, since this codebase is written in ES5, new code I would think should conform with something like:

```
var host = process.env.HOST;
var port = process.env.PORT;

host = host ? host : 'localhost';
port = port ? port : 3000;
```

**Comment by pdavidow** [comment]
I am stuck on manual testing: Unable to set HOST in bash shell.

**Comment by ericelliott** [comment]
1. This codebase is written in ES6.
2. If `HOST` is reserved, I'm happy using something less generic like `PC_HOST` and `PC_PORT`

**Comment by pdavidow** [comment]
When I try to send Pull Request, I get _Authentication Failed_.

**Comment by ericelliott** [comment]
@pdavidow Have you set up your [GitHub SSH Keys](https://help.github.com/articles/generating-an-ssh-key/)?

**Comment by pdavidow** [comment]
The SSH keys are all set, but it still doesn't help.
Instead, I have pushed branch here: https://github.com/pdavidow/react-pure-component-starter

(Tested manually on Cloud9, and Mac OSX)

**Comment by ericelliott** [comment]
If you delete that and just hit the fork button on this repo, then pull your fork and merge your changes into that, then push your changes to your fork, you should be able to submit a pull request. You should see a yellow button pop up asking if you want to submit a PR.

**Comment by ericelliott** [comment]
See [Forking a repo](https://help.github.com/articles/fork-a-repo/)

**Comment by pdavidow** [comment]
The deed has been done, I think. A yellow button (actually, a yellow ring) did pop up, but all it's doing is notifying me of pending CI tests -- it's not asking me to submit a PR.  (Anyway, the reason it didn't originally work is because I had cloned without making a fork.)

**Comment by ericelliott** [comment]
Nice.. I'll look over it asap

**Comment by pdavidow** [comment]
How would you write tests for this?

**Comment by ericelliott** [comment]
Set the environment variable. Launch the server. Use something like supertest to make sure the server responds appropriately to requests on the specified host/port.
