### ISSUE TITLE
Windows is not supported

### ISSUE THREAD

**Issue by pdavidow** [ericelliott/react-pure-component-starter#230]
Mention in readme that Windows is not currently supported.

**Comment by ericelliott** [comment]
Sure. We should also invite people to submit a PR to fix the issue. Want to make a PR for the README? You're also welcome to make a PR to add windows support if you like. =)

**Comment by pdavidow** [comment]
Still have problem:
https://gitter.im/learn-javascript-courses/javascript-questions?at=5817be16806316005ddf2219

**Comment by ericelliott** [comment]
Looks like we need a cross-platform clear screen. I believe windows has `cls` and unix uses `clear`.

**Comment by Burgi0101** [comment]
Added a PR for full cross-platform support! https://github.com/ericelliott/react-pure-component-starter/pull/238
