### ISSUE TITLE
Dependency injection: just the React instance?

### ISSUE THREAD

**Issue by matteocng** [ericelliott/react-pure-component-starter#234]
Is it recommended to inject the instances of the other packages on which the component depends? e.g:

``` js
export default (React, CssModules, classnames) => (props) => <h1>{ props.title }</h1>
```

The injected packages could then be moved from 'dependencies' to 'peerDependencies' in the library's package.json.

**Comment by ericelliott** [comment]
Direct dependencies on something as simple as `classnames` is fine. I'm unaware of problems from duplicate `CssModules` -- are you?

I began using the `React` injection because there were specific problems with getting duplicate copies of React used in the same codebase.
