### ISSUE TITLE
React instance injection ?

### ISSUE THREAD

**Issue by gouegd** [ericelliott/react-pure-component-starter#3]
> Pure component factories let you inject your React instance into the component so that you can share a single React instance across your entire app -- even if you load React from CDN for client use

I can't see the advantage over using ES6 `import React from 'react'` on each file - besides the repeated 1-line advantage, obviously. That, and the classic-er ES5 `require` call provided by libs, gives you one same React instance on all components too. Am I missing something ?

**Comment by ericelliott** [comment]
Yep. You're missing the  fact that lots of apps load React from CDN for front-end code, as well as the fact that front end code may have more than one entry point (and may in fact be two completely different codebases) -- if both entry points use React, you'll get conflicts. Exporting a factory is the safest way to mitigate the situation.

For more on this problem and how common it is, see [Two React Tips](https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375) by Dan Abramov.

**Comment by gouegd** [comment]
Thanks for the details! :)

**Comment by ericelliott** [comment]
:+1:

**Comment by hoschi** [comment]
> more than one entry point (and may in fact be two completely different codebases) [...] For more on this problem and how common it is, see Two React Tips by Dan Abramov.

This explanation should be added to the paragraph cited by OP. Current text in readme states the "how" pretty good, but leaves the "why" untouched. Loading React from CDN doesn't imply directly other problems like "installed a library which requires React by itself" (mentioned in linked article), at least to me and @gouegd

**Comment by ericelliott** [comment]
Open to a PR.
