### ISSUE TITLE
using enzyme and cherrio

### ISSUE THREAD

**Issue by gavriguy** [ericelliott/react-pure-component-starter#39]
i see you are using both enzyme and cherrio libs for testing and i wonder why.
isn't cherrio full render enough?
and if not why not using the render function from enzyme and remove cherrio dependency altogether

**Comment by ericelliott** [comment]
I was experimenting with Enzyme. I was hoping I could use it to test component events, which AFAIK, you can't do with Cheerio. However, that didn't work out too well. Still hopeful it will improve in the future.

**Comment by gavriguy** [comment]
Thanks.
